version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${PWD}/keys/:/app/keys