version: '3.3'

services:
  backend:
    # image: ghcr.io/psychobilly13/pdfconverter-backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${PWD}/keys/:/app/keys